import { useState } from "react";
import { useMutation, useQuery, useAction } from "convex/react";
import { api } from "../../convex/_generated/api";
import { motion } from "framer-motion";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { Card, CardContent } from "@/components/ui/card";
import { Sparkles, Quote, Loader2, Wand2 } from "lucide-react";

interface AddPhrasePageProps {
  onPhraseAdded: () => void;
}

export function AddPhrasePage({ onPhraseAdded }: AddPhrasePageProps) {
  const [text, setText] = useState("");
  const [source, setSource] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);

  const addPhrase = useMutation(api.phrases.addPhrase);
  const generatePhrase = useAction(api.phrases.generatePhrase);
  const randomPhrase = useQuery(api.phrases.getRandomPhrase);
  const totalCount = useQuery(api.phrases.listPhrases, {})?.length || 0;

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!text.trim()) return;

    setIsSubmitting(true);
    try {
      await addPhrase({
        text: text.trim(),
        source: source.trim() || undefined,
      });

      setText("");
      setSource("");
      toast.success("Phrase captured", {
        description: "AI is categorizing your wisdom...",
        action: {
          label: "View",
          onClick: onPhraseAdded,
        },
      });
    } catch (error) {
      toast.error("Failed to add phrase");
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleGenerate = async () => {
    setIsGenerating(true);
    try {
      const result = await generatePhrase();
      setText(result.text);
      setSource(result.source);
      toast.success("Phrase generated by AI");
    } catch (error) {
      toast.error("Failed to generate phrase", {
        description: "Please check your API key settings."
      });
    } finally {
      setIsGenerating(false);
    }
  };

  const handleQuickAdd = (phraseText: string) => {
    setText(phraseText);
  };

  const quickPhrases = [
    "The only way to do great work is to love what you do.",
    "Life is what happens to you while you're busy making other plans.",
    "In the middle of difficulty lies opportunity.",
    "The future belongs to those who believe in the beauty of their dreams.",
  ];

  return (
    <div className="flex flex-col items-center justify-center min-h-[80vh] w-full max-w-3xl mx-auto">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
        className="text-center mb-12 space-y-4"
      >
        <div className="inline-flex items-center justify-center p-3 rounded-full bg-secondary/30 mb-4 animate-float">
          <Sparkles className="w-6 h-6 text-white" />
        </div>
        <h1 className="text-4xl md:text-6xl font-bold tracking-tighter text-balance">
          Capture Your Wisdom
        </h1>
        <p className="text-lg text-muted-foreground max-w-lg mx-auto text-balance">
          Save meaningful phrases, quotes, and thoughts. Let AI organize them for you.
        </p>
      </motion.div>

      <motion.div
        initial={{ opacity: 0, y: 30 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6, delay: 0.2 }}
        className="w-full"
      >
        <Card className="border-white/5 bg-zinc-900/50 backdrop-blur-xl shadow-2xl">
          <CardContent className="p-8">
            <form onSubmit={handleSubmit} className="space-y-6">
              <div className="space-y-2">
                <label className="text-sm font-medium text-muted-foreground ml-1 flex items-center justify-between">
                  <span>Your Phrase</span>
                  <Button
                    type="button"
                    variant="ghost"
                    size="sm"
                    onClick={handleGenerate}
                    disabled={isGenerating || isSubmitting}
                    className="h-6 text-xs text-blue-400 hover:text-blue-300 hover:bg-blue-400/10"
                  >
                    {isGenerating ? (
                      <Loader2 className="w-3 h-3 mr-1 animate-spin" />
                    ) : (
                      <Wand2 className="w-3 h-3 mr-1" />
                    )}
                    Generate with AI
                  </Button>
                </label>
                <div className="relative">
                  <Textarea
                    value={text}
                    onChange={(e) => setText(e.target.value)}
                    placeholder="Enter a meaningful phrase, quote, or thought..."
                    className="min-h-[120px] text-lg bg-black/20 border-white/10 focus:border-white/20 resize-none p-4 leading-relaxed"
                    disabled={isSubmitting}
                  />
                  <Quote className="absolute right-4 top-4 w-5 h-5 text-muted-foreground/20" />
                </div>
              </div>

              <div className="space-y-2">
                <label className="text-sm font-medium text-muted-foreground ml-1">
                  Source <span className="text-muted-foreground/50">(Optional)</span>
                </label>
                <Input
                  type="text"
                  value={source}
                  onChange={(e) => setSource(e.target.value)}
                  placeholder="Book, author, website, or person..."
                  className="bg-black/20 border-white/10 focus:border-white/20 h-12"
                  disabled={isSubmitting}
                />
              </div>

              <Button
                type="submit"
                disabled={!text.trim() || isSubmitting}
                className="w-full h-12 text-base font-medium bg-white text-black hover:bg-gray-200 transition-all duration-300"
              >
                {isSubmitting ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Adding Phrase...
                  </>
                ) : (
                  "Add to Collection"
                )}
              </Button>
            </form>
          </CardContent>
        </Card>
      </motion.div>

      {/* Quick Add Section */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.6, delay: 0.4 }}
        className="mt-12 w-full grid grid-cols-1 md:grid-cols-2 gap-4"
      >
        {quickPhrases.map((phrase, index) => (
          <button
            key={index}
            onClick={() => handleQuickAdd(phrase)}
            className="text-left p-4 rounded-xl bg-secondary/10 hover:bg-secondary/20 border border-white/5 hover:border-white/10 transition-all duration-200 text-sm text-muted-foreground hover:text-foreground"
          >
            "{phrase}"
          </button>
        ))}
      </motion.div>

      {/* Footer Stats */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.6, delay: 0.6 }}
        className="mt-12 text-sm text-muted-foreground"
      >
        {totalCount > 0 ? (
          <span>{totalCount} phrases collected so far</span>
        ) : (
          <span>Start your collection today</span>
        )}
      </motion.div>
    </div>
  );
}
